File operations
NetApp/ontap-rest-python pull request #41
Opened 2023-07-07 15:40 UTC by bmrussell

Hi - I noteced there were no examples of file handling in the Python client library. I noticed the examples shown in the documentation didn't quite work. This code runs successfully on the NetApp Labs environment.

It:
- Enumerates volumes to find the requested volume (instead of using .get(), just to demonstrate)
- Creates a folder structure with files
- Lists that structure recursively
- Cleans up

Hope this helps others.

2023-09-25 21:40 UTC, noorbuchi requested changes
Thanks for adding this great example! I have few suggestions. Once addressed, it should be good to merge.

2023-09-25 21:40 UTC, noorbuchi commented on examples/python_client_library/file_operations.py
> +        "This script will demo          nstrate enumerating volumes, file and directory creation, file and directory creation deletion",
nitpick: spacing issue with demonstrate

2023-09-25 21:40 UTC, noorbuchi commented on examples/python_client_library/file_operations.py
> +            if vol.name == volume_name:
This can be replaced with [`Volume.find()`](https://library.netapp.com/ecmdocs/ECMLP2885777/html/resources/volume.html#netapp_ontap.resources.volume.Volume.find) which does a very similar thing internally. Alternatively, you can pass the name of the volume as a query parameter to get collection `Volume.get_collection(name="vol_name")`. This will return a list of volumes matching this query

2023-09-29 08:28 UTC, bmrussell commented on examples/python_client_library/file_operations.py
> +        "This script will demo          nstrate enumerating volumes, file and directory creation, file and directory creation deletion",
Thanks @noorbuchi . Silly typo. Pushed a fix to the branch.

2023-09-30 18:10 UTC, noorbuchi requested changes
Thanks for making the fixes and apologies for the late response. I ran the linting checks and they're currently failing. Can you please add fixes so that the build is passing. We should be good to merge after. Thanks!

2023-10-02 10:35 UTC, bmrussell commented
Thanks for the heads up @noorbuchi, the module lints cleanly locally now. Might be worth a reminder to lint in CONTRIBUTING.md?

2023-10-02 21:05 UTC, noorbuchi approved these changes

2023-10-02 21:06 UTC, merged